version: "3.3"

services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0.27
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=trojan_box
      - MYSQL_ROOT_HOST=%
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password

  warehouse:
    image: aresprotocollab/trojan-box:latest
    container_name: trojan-box
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "5577:5577"
    volumes:
      - ./config:/opt/config:ro
      - ./logs:/opt/logs
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      sh -c "ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtim &&
      echo $$TZ > /etc/timezone &&
      exec /opt/trojan-box"

