// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/config": {
            "get": {
                "description": "get app config info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "GetAppConfig",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.Config"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bonus/histories": {
            "get": {
                "description": "get user bonus history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonus"
                ],
                "summary": "GetUserBonusHistory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "1：win 2：withdraw",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.BonusHistory"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bonus/my": {
            "get": {
                "description": "get my bonus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonus"
                ],
                "summary": "GetMyBonus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.UserBonus"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bonus/my/history": {
            "get": {
                "description": "get my bonus history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonus"
                ],
                "summary": "GetMyBonusHistory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.BonusHistory"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bonus/withdraw/apply": {
            "post": {
                "description": "apply to withdraw bonus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonus"
                ],
                "summary": "WithdrawBonusApply",
                "parameters": [
                    {
                        "description": "req",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.WithdrawBonusApplyReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bonus_pool/info": {
            "get": {
                "description": "get bonus pool info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonus_pool"
                ],
                "summary": "GetBonusPoolInfo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.BonusPoolInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/broadcast": {
            "get": {
                "description": "get broadcasts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "broadcast"
                ],
                "summary": "GetBroadcasts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "language",
                        "name": "lang",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/broadcast/latest": {
            "get": {
                "description": "get the latest broadcast",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "broadcast"
                ],
                "summary": "GetLatestBroadcast",
                "parameters": [
                    {
                        "type": "string",
                        "description": "language",
                        "name": "lang",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/file/upload": {
            "post": {
                "description": "uploadFile",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "UploadFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/game/histories": {
            "get": {
                "description": "get all user played game history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "GetGameHistory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter address ,if empty will query all address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.GameHistories"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/game/id/{id}": {
            "get": {
                "description": "get played game detail by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "GetGameDetailById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.GameSession"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/game/my/history": {
            "get": {
                "description": "get my played game history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "GetMyGameHistory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.GameHistory"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/game/play": {
            "post": {
                "description": "play game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "PlayGame",
                "parameters": [
                    {
                        "description": "req",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.PlayGameReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.PlayGameResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/game/{session}": {
            "get": {
                "description": "get played game detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "GetGameDetail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "session str",
                        "name": "session",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.GameSession"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/gas/cal": {
            "get": {
                "description": "calculate gas to ares",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gas"
                ],
                "summary": "CalGasFee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "gas",
                        "name": "gas",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/leaderboard": {
            "get": {
                "description": "get leaderboard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leaderboard"
                ],
                "summary": "GetLeaderboard",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "type: 1: newStar 2:season champion",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/vo.LeaderboardResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/message/my": {
            "get": {
                "description": "get my message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "GetMyMessages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "language",
                        "name": "lang",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "state 1：unRead 2:read",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.UserMessage"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/message/read": {
            "post": {
                "description": "make message read",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "ReadMessage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "req",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.ReadMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/nonce": {
            "get": {
                "description": "get user nonce by address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nonce"
                ],
                "summary": "get nonce",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/share": {
            "get": {
                "description": "get  bonus withdraw ,can filter by address and type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "GetSocialShares",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter address,if empty will return all user",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter auditor_address",
                        "name": "auditor_address",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "state 0：unProcess 1:processing 2:processed",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "type 1:withdraw 2:common",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "type 1:Gate 2:Weibo 3:Twitter 4:Reddit 5:Facebook",
                        "name": "channel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.SocialShare"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "add social share",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "CreateSocialShare",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "addReq",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.AddSocialShareReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/share/my": {
            "get": {
                "description": "get my social shares",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "GetMySocialShares",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "state 0：unProcess 1:processing 2:processed",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "type 1:withdraw 2:common",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "type 1:Gate 2:Weibo 3:Twitter 4:Reddit 5:Facebook",
                        "name": "channel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "begin time",
                        "name": "beginTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "end time",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.SocialShare"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/share/process": {
            "post": {
                "description": "process social share",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "SocialShareProcess",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "req",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.ProcessSocialShareReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/stats/daily": {
            "get": {
                "description": "get daily stats",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "GetDailyStats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query day",
                        "name": "day",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.DailyStats"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/stats/daily/list": {
            "get": {
                "description": "get daily stats list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "GetDailyStatsList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.DailyStats"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/stats/total": {
            "get": {
                "description": "get total stats,will cache 1 minute",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "GetTotalStats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.TotalStats"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/stats/yield/hourly": {
            "get": {
                "description": "get user yield hourly list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "GetDailyStatsList",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.UserYieldHourlyStats"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/auth": {
            "post": {
                "description": "user login and get accessToken",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "auth",
                "parameters": [
                    {
                        "description": "auth",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.UserAuthReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "description": "get user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "getUserProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vo.UserProfile"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "modify user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "modifyUserProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "modifyReq",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.ModifyUserProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/withdraw/histories": {
            "get": {
                "description": "get  bonus withdraw ,can filter by address and type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "withdraw"
                ],
                "summary": "GetWithdraws",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter address,if empty will return all user",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "type 0：unProcess 1:processing 2:processed",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.BonusWithdraw"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/withdraw/my/history": {
            "get": {
                "description": "get my bonus withdraw ,can filter by type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "withdraw"
                ],
                "summary": "GetMyWithdraws",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "type 0：unProcess 1:processing 2:processed",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page start from 0,default 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size default 20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/vo.Pagination"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "items": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/vo.BonusWithdraw"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/withdraw/process": {
            "post": {
                "description": "process withdraw bonus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "withdraw"
                ],
                "summary": "WithdrawBonusProcess",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "req",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.ProcessWithdrawBonusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/withdraw/report_tx": {
            "post": {
                "description": "report processed withdraw tx hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "withdraw"
                ],
                "summary": "WithdrawReportHash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accessToken",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "req",
                        "name": ".",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/vo.ProcessWithdrawBonusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "vo.AddSocialShareReq": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "share_type": {
                    "type": "integer"
                }
            }
        },
        "vo.BonusHistory": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "associate": {
                    "type": "integer"
                },
                "bonus": {
                    "type": "integer"
                },
                "create_time": {
                    "type": "integer"
                },
                "state": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "vo.BonusPoolInfo": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                }
            }
        },
        "vo.BonusWithdraw": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "apply_time": {
                    "type": "integer"
                },
                "bonus": {
                    "type": "integer"
                },
                "gas": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "state": {
                    "type": "integer"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "vo.Config": {
            "type": "object",
            "properties": {
                "debug": {
                    "type": "boolean"
                },
                "game": {
                    "$ref": "#/definitions/vo.GameConfig"
                },
                "manager_address": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mode": {
                    "type": "string"
                },
                "white_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.DailyStats": {
            "type": "object",
            "properties": {
                "annual_yield_rate": {
                    "type": "number"
                },
                "day": {
                    "type": "string"
                },
                "game_reward_amount": {
                    "type": "integer"
                },
                "new_address": {
                    "type": "integer"
                },
                "opened_big_reward": {
                    "type": "integer"
                },
                "part_in_address": {
                    "type": "integer"
                },
                "part_in_count": {
                    "type": "integer"
                },
                "reward_amount": {
                    "type": "integer"
                },
                "share_reward_amount": {
                    "type": "integer"
                },
                "single_reward_max": {
                    "type": "integer"
                },
                "single_reward_min": {
                    "type": "integer"
                },
                "staking_amount": {
                    "type": "integer"
                },
                "unopened_big_reward": {
                    "type": "integer"
                },
                "withdraw_amount": {
                    "type": "integer"
                }
            }
        },
        "vo.GameConfig": {
            "type": "object",
            "properties": {
                "end_hour": {
                    "type": "integer"
                },
                "min_balance": {
                    "type": "integer"
                },
                "min_withdraw": {
                    "type": "integer"
                },
                "only_white_list": {
                    "type": "boolean"
                },
                "start_hour": {
                    "type": "integer"
                },
                "verify_wallet_balance": {
                    "type": "boolean"
                }
            }
        },
        "vo.GameHistories": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bonus": {
                    "type": "integer"
                },
                "cards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "cards_bonus": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chosen_index": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "play_time": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                }
            }
        },
        "vo.GameHistory": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bonus": {
                    "type": "integer"
                },
                "cards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "cards_bonus": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chosen_index": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "play_time": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                }
            }
        },
        "vo.GameSession": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bonus": {
                    "type": "integer"
                },
                "cards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "cards_bonus": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chosen_index": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "play_time": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                }
            }
        },
        "vo.LeaderboardResp": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer"
                }
            }
        },
        "vo.ModifyUserProfileReq": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                }
            }
        },
        "vo.Pagination": {
            "type": "object",
            "properties": {
                "curPage": {
                    "type": "integer"
                },
                "items": {},
                "totalNum": {
                    "type": "integer"
                }
            }
        },
        "vo.PlayGameReq": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chosen": {
                    "type": "integer"
                },
                "nonce": {
                    "type": "string"
                },
                "signed_msg": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "vo.PlayGameResp": {
            "type": "object",
            "properties": {
                "bonus": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                }
            }
        },
        "vo.ProcessSocialShareReq": {
            "type": "object",
            "properties": {
                "accept": {
                    "type": "boolean"
                },
                "auditor": {
                    "type": "string"
                },
                "bonus": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "reply": {
                    "type": "string"
                }
            }
        },
        "vo.ProcessWithdrawBonusReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "txhash": {
                    "type": "string"
                }
            }
        },
        "vo.ReadMessage": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "vo.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "vo.SocialShare": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "apply_time": {
                    "type": "integer"
                },
                "auditor": {
                    "type": "string"
                },
                "auditor_address": {
                    "type": "string"
                },
                "bonus": {
                    "type": "integer"
                },
                "channel": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "reply": {
                    "type": "string"
                },
                "share_type": {
                    "type": "integer"
                },
                "state": {
                    "type": "integer"
                }
            }
        },
        "vo.TotalStats": {
            "type": "object",
            "properties": {
                "avg_apr": {
                    "type": "number"
                },
                "game_reward_amount": {
                    "type": "integer"
                },
                "part_in_address": {
                    "type": "integer"
                },
                "part_in_count": {
                    "type": "integer"
                },
                "reward_amount": {
                    "type": "integer"
                },
                "share_reward_amount": {
                    "type": "integer"
                },
                "signed_address": {
                    "type": "integer"
                },
                "staking_amount": {
                    "type": "integer"
                },
                "withdraw_amount": {
                    "type": "integer"
                }
            }
        },
        "vo.UserAuthReq": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "signed_msg": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "vo.UserBonus": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "integer"
                },
                "freeze": {
                    "type": "integer"
                },
                "today_win": {
                    "type": "integer"
                },
                "total_win": {
                    "type": "integer"
                }
            }
        },
        "vo.UserMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "state": {
                    "type": "integer"
                }
            }
        },
        "vo.UserProfile": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                }
            }
        },
        "vo.UserYieldHourlyStats": {
            "type": "object",
            "properties": {
                "annually_rate": {
                    "type": "number"
                },
                "balance": {
                    "type": "integer"
                },
                "reward": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "vo.WithdrawBonusApplyReq": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bonus": {
                    "type": "integer"
                },
                "nonce": {
                    "type": "string"
                },
                "signed_msg": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
